EMAIL_SUBJECT = "TNP Made Easy by Amey | StudentDetails | {}"
EMAIL_FROM = 'no.reply.tnpproject@gmail.com'
EMAIL_TO = ['bamey2241997@gmail.com','aadityab134@gmail.com','danimanas28@gmail.com']
MESSAGE_BODY = "Please find attached File with the requested Details."
PATH_TO_CSV_FILE = "C:\\Users\\lenovo\\data structure in python\\BE project\\relationalDBManagementSystem\\backEnd\\outputs\\StudentDetails.csv"
FILE_NAME = "studentDetails_{}.csv"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "no.reply.tnpproject@gmail.com"
SMTP_PASSWORD = "aykewuftgquwrshm"
